[build]
publish = "."
command = ""

[[redirects]]
from = "/api/*"
to = "https://vaultra-zacl.onrender.com/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"